services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command: --config /oauth2-proxy.cfg
    restart: unless-stopped
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
