---
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.http.routers.dozzle-https.entrypoints: websecure
      traefik.http.routers.dozzle-https.rule: "Host(`${FQDN}`)"
      traefik.http.routers.dozzle-https.tls: true
      traefik.http.routers.dozzle-https.tls.certresolver: cloudflare
      traefik.http.routers.dozzle-https.middlewares: tinyauth
      traefik.http.services.dozzle-https.loadbalancer.server.port: 8080
      com.centurylinklabs.watchtower.enable: true
    networks:
      - frontend

networks:
  frontend:
    external: true
