---
services:
  forgejo-server:
    container_name: forgejo-server
    image: codeberg.org/forgejo/forgejo:11
    restart: unless-stopped
    environment:
      USER_UID: $PUID
      USER_GID: $PGID
      FORGEJO__repository__ENABLE_PUSH_CREATE_USER: true
      # FORGEJO__database__DB_TYPE: postgres
      # FORGEJO__database__HOST: forgejo-postgres-db:5432
      # FORGEJO__database__NAME: forgejo
      # FORGEJO__database__USER: $DB_USERNAME
      # FORGEJO__database__PASSWD: $DB_PASSWORD
    volumes:
      - $VOLUME/forgejo/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.http.routers.forgejo-https.entrypoints: websecure
      traefik.http.routers.forgejo-https.rule: "Host(`${FQDN}`)"
      traefik.http.routers.forgejo-https.tls: true
      traefik.http.routers.forgejo-https.tls.certresolver: cloudflare
      traefik.http.services.forgejo-https.loadbalancer.server.port: 3000
      # traefik.http.routers.forgejo-https.middlewares: tinyauth
      com.centurylinklabs.watchtower.enable: true
    ports:
    - $SSH_PORT:22
    networks:
      - frontend
      # - backend
    # depends_on:
    #   - forgejo-postgres-db

  # forgejo-postgres-db:
  #   container_name: forgejo-postgres-db
  #   image: postgres:14
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: $DB_USERNAME
  #     POSTGRES_PASSWORD: $DB_PASSWORD
  #     POSTGRES_DB: forgejo
  #   volumes:
  #     - $VOLUME/forgejo/postgres:/var/lib/postgresql/data
  #     # TRY A NAMED VOLUME
  #     - forgejo-postgres-db:/var/lib/postgresql/data
  #   networks:
  #     - backend

networks:
  frontend:
    external: true
  # backend:
  #   external: true
