global:
  checkNewVersion: false
  sendAnonymousUsage: false

accessLog: {}

log:
  # level: INFO
  level: DEBUG

# accessLog:
#   filePath: '/logs/access.log'

api:
  dashboard: false
  insecure: true
  debug: false

# http:
#   middlewares:
#     oauth2-auth:
#       forwardAuth:
#         address: http://oauth2-proxy:4180/oauth2/auth
#         trustForwardHeader: true
#         authResponseHeaders:
#           - X-Auth-Request-User
#           - X-Auth-Request-Email
#           - Set-Cookie

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  cloudflare:
    acme:
      email: 'dpi0.dev@proton.me'
      # internal path to traefik
      storage: /etc/traefik/certs/cloudflare-acme.json
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - '1.1.1.1:53'
          - '8.8.8.8:53'

serversTransport:
  insecureSkipVerify: true

providers:
  # file:
  #   filename: /config.yml
  #   watch: true
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    watch: true
    # only exposes the services with the label `ai.ix.expose=true`
    # constraints: "Label(`ai.ix.expose`, `true`)"
    # if no rule exists, it uses the value of the label `ai.ix.fqdn` for Host(``)
    # defaultRule: "Host(`{{ index .Labels \"ai.ix.fqdn\"}}`)"
