---
services:
  backrest:
    container_name: backrest
    # image: garethgeorge/backrest:latest
    image: ghcr.io/dpi0/backrest-rsync:main
    restart: unless-stopped
    environment:
      PUID: $PUID
      GID: $GID
      TZ: $TZ
      BACKREST_PORT: 9898
      BACKREST_DATA: /data
      BACKREST_CONFIG: /config/config.json
      XDG_CACHE_HOME: /cache
      TMPDIR: /tmp
    hostname: backrest
    volumes:
      - $VOLUME/backrest/data:/data
      - $VOLUME/backrest/config:/config
      - $VOLUME/backrest/cache:/cache
      - $VOLUME/backrest/tmp:/tmp
      - $HOME:$HOME
      - $HOME/.ssh:/root/.ssh
      - $BACKUP:$BACKUP
      - $IMMICH:$IMMICH
      - $ROOT:/rootlab
      - $SENSITIVE:$SENSITIVE
      - $SPACE:$SPACE
      - $VOLUME/backrest/rclone:/root/.config/rclone
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.backrest-https.entrypoints: websecure
      traefik.http.routers.backrest-https.rule: "Host(`${FQDN}`)"
      traefik.http.routers.backrest-https.tls: true
      traefik.http.routers.backrest-https.tls.certresolver: cloudflare
      # traefik.http.routers.backrest-https.middlewares: tinyauth
      traefik.http.services.backrest-https.loadbalancer.server.port: 9898
      com.centurylinklabs.watchtower.enable: true
    # ports:
    #   - 1009:9898
    networks:
      - frontend

networks:
  frontend:
    external: true
