---
services:
  pocket-id:
    container_name: pocket-id
    image: ghcr.io/pocket-id/pocket-id
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      PUBLIC_APP_URL: 'https://${FQDN}'
      # MAXMIND_LICENSE_KEY: ""
      TRUST_PROXY: true
    volumes:
      - $VOLUME/pocket-id/data:/app/backend/data
    healthcheck:
      test: "curl -f http://localhost/healthz"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    labels:
      traefik.enable: true
      traefik.http.routers.pocket-id.entrypoints: websecure
      traefik.http.routers.pocket-id.rule: "Host(`${FQDN}`)"
      traefik.http.routers.pocket-id.tls: true
      traefik.http.routers.pocket-id.tls.certresolver: cloudflare
      traefik.http.services.pocket-id.loadbalancer.server.port: 80
      com.centurylinklabs.watchtower.enable: true
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true
