---
services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    restart: unless-stopped
    environment:
      GLANCES_OPT: -w
    pid: host
    volumes:
      - ./config/glances.conf:/glances/conf/glances.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.glances-https.entrypoints: websecure
      traefik.http.routers.glances-https.rule: "Host(`${FQDN}`)"
      traefik.http.routers.glances-https.tls: true
      traefik.http.routers.glances-https.tls.certresolver: cloudflare
      traefik.http.routers.glances-https.middlewares: tinyauth
      com.centurylinklabs.watchtower.enable: true
    # ports:
    #   - 1003:61208
    networks:
      - frontend

networks:
  frontend:
    external: true
