---
services:
  portainer:
    container_name: portainer
    # image: portainer/portainer-ce:sts
    # image: portainer/portainer-ce:2.21.4
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - $VOLUME/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    # command: -H unix:///var/run/docker.sock --base-url="/admin/portainer"
    labels:
      traefik.enable: true
      traefik.http.routers.portainer-https.entrypoints: websecure
      traefik.http.routers.portainer-https.rule: "Host(`${FQDN}`)"
      traefik.http.routers.portainer-https.tls: true
      # found this error by looking at traefik logs in /var/log/traefik/traefik.log
      # look for 'ERR' (when DEBUG or ERROR) log mode is present not on INFO
      # for example this was the error i caught
      # 2025-06-01T19:19:42+05:30 ERR github.com/traefik/traefik/v3/pkg/provider/configuration.go:497 > Router portainer-https cannot be linked automatically with multiple Services: 
      # ["portainer-https" "portainer-tailscale"] providerName=docker routerName=portainer-https
      traefik.http.routers.portainer-https.service: portainer-https
      traefik.http.routers.portainer-https.tls.certresolver: cloudflare
      # traefik.http.routers.portainer-https.middlewares: portainer-https-stripprefix@docker
      # traefik.http.middlewares.portainer-https-stripprefix.stripprefix.prefixes: /portainer
      traefik.http.services.portainer-https.loadbalancer.server.port: 9000

      traefik.http.routers.portainer-tailscale.entryPoints: websecure
      traefik.http.routers.portainer-tailscale.rule: "Host(`${FQDN_TAILSCALE}`)"
      traefik.http.routers.portainer-tailscale.service: portainer-tailscale
      traefik.http.routers.portainer-tailscale.tls: true
      traefik.http.routers.portainer-tailscale.tls.certresolver: cloudflare
      traefik.http.services.portainer-tailscale.loadbalancer.server.port: 9000

      com.centurylinklabs.watchtower.enable: true
    # ports:
    #   - 1002:9443
    networks:
      - frontend

networks:
  frontend:
    external: true
