---
services:
  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.it-tools.entrypoints: websecure
      traefik.http.routers.it-tools.rule: "Host(`${FQDN}`)"
      traefik.http.routers.it-tools.tls: true
      traefik.http.routers.it-tools.tls.certresolver: cloudflare
      # traefik.http.routers.it-tools.middlewares: tinyauth
      # traefik.http.routers.it-tools.middlewares: 'authelia@docker'
      # traefik.http.routers.it-tools.middlewares: oauth2-proxy@docker
      traefik.http.services.it-tools.loadbalancer.server.port: 80
      com.centurylinklabs.watchtower.enable: true
      # sablier.enable: true
      # sablier.group: testing
    networks:
      - frontend

networks:
  frontend:
    external: true
