---
services:
  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.it-tools.entrypoints: websecure
      traefik.http.routers.it-tools.rule: "Host(`${FQDN}`)"
      traefik.http.routers.it-tools.tls: true
      traefik.http.routers.it-tools.tls.certresolver: cloudflare
      traefik.http.services.it-tools.loadbalancer.server.port: 80
      traefik.http.routers.it-tools.middlewares: it-tools-auth@docker

      traefik.http.middlewares.it-tools-auth.basicauth.users: "admin:$$2y$$05$$Q.I0mqw8b3XvcU7A1qjnzupFJFovc3rFLG7bWBnhN3oVt1eXfjGc."
      com.centurylinklabs.watchtower.enable: true
    networks:
      - frontend

networks:
  frontend:
    external: true
