---
services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      GID: $GID
      TZ: $TZ
    volumes:
      - $VOLUME/syncthing/config:/config
      - $HOME:$HOME
      - $BACKUP:$BACKUP
    labels:
      traefik.enable: true
      traefik.http.routers.syncthing-https.entrypoints: websecure
      traefik.http.routers.syncthing-https.rule: "Host(`${FQDN}`)"
      traefik.http.routers.syncthing-https.tls: true
      traefik.http.routers.syncthing-https.tls.certresolver: cloudflare
      # traefik.http.routers.syncthing-https.middlewares: tinyauth
      com.centurylinklabs.watchtower.enable: true
    # ports:
    #   - 22000:22000/udp
    #   - 21027:21027/udp
    networks:
      - frontend

networks:
  frontend:
    external: true
