---
services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - $VOLUME/glance/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      # traefik.http.routers.glance-http.entrypoints: web
      # traefik.http.routers.glance-http.rule: "Host(`${FQDN}`)"
      traefik.http.routers.glance-https.entrypoints: websecure
      traefik.http.routers.glance-https.rule: "Host(`${FQDN}`)"
      traefik.http.routers.glance-https.tls: true
      traefik.http.routers.glance-https.tls.certresolver: cloudflare
      traefik.http.routers.glance-https.middlewares: tinyauth

      traefik.http.routers.glance-tailscale.rule: "Host(`${FQDN_TAILSCALE}`)"
      traefik.http.routers.glance-tailscale.entryPoints: websecure
      traefik.http.routers.glance-tailscale.tls: true
      traefik.http.routers.glance-tailscale.tls.certresolver: cloudflare
      # traefik.http.routers.glance-tailscale.middlewares: tinyauth

      com.centurylinklabs.watchtower.enable: true

      glance.name: Glance
      glance.url: $FQDN
      glance.id: glance
    # ports:
    #   - 1001:8080
    networks:
      - frontend

networks:
  frontend:
    external: true
